src/main/java/br/com/leonardo/praticas/model/AbstractEntity.java
package br.com.leonardo.praticas.model;

import java.io.Serializable;

public interface AbstractEntity extends Serializable {

    public Number getId();

}

src/main/java/br/com/leonardo/praticas/mb/CrudNavegavelMB.java
package br.com.leonardo.praticas.mb;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.hibernate.exception.ConstraintViolationException;

import br.com.leonardo.praticas.model.AbstractEntity;
import br.com.leonardo.praticas.service.AbstractPersistence;

public abstract class CrudNavegavelMB<T extends AbstractEntity> extends NavegavelMB {

    private static final String ID_SELECIONADO = "idSelecionado";
    private static final String SUCESSO_SALVAR = "sucessoSalvar";
    private static final String SUCESSO_REMOVER = "sucessoRemover";

    public CrudNavegavelMB(Class<T> classeEntidade) {
        Boolean sucessoSalvar = (Boolean) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get(SUCESSO_SALVAR);
        Boolean sucessoRemover = (Boolean) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get(SUCESSO_REMOVER);

        if (sucessoSalvar != null && sucessoSalvar) {
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(SUCESSO_SALVAR, null);
            addMessage(FacesMessage.SEVERITY_INFO, getMessageFromI18N("aplicativo.msg.sucesso.salvar"), null);
        }

        if (sucessoRemover != null && sucessoRemover) {
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(SUCESSO_REMOVER, null);
            addMessage(FacesMessage.SEVERITY_INFO, getMessageFromI18N("aplicativo.msg.sucesso.remover"), null);
        }

        this.classeEntidade = classeEntidade;
    }

    protected Class<T> classeEntidade;

    private T model;

    private List<T> listaFiltrada;

    public abstract AbstractPersistence<T, Number> getService();

    public abstract String getDiretorio();

    public abstract String getLabel();

    public String getActionListar() {
        return "/" + getDiretorio() + "/" + "listar";
    }

    public String getActionEditar() {
        return "/" + getDiretorio() + "/" + "editar";
    }

    public String getMenuListar() {
        return getDiretorio() + "listar";
    }

    public void preSave() {
    }

    public void postSave() {
    }

    public List<T> getListar() {
        return getService().findAll();
    }

    public void novo() {
        try {
            model = classeEntidade.newInstance();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }

    public String carregar(Number idSelecionado) {
        if (idSelecionado != null) {
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(ID_SELECIONADO, idSelecionado);
        }
        return iniciar(getMenu(), getActionEditar());
    }

    public String salvar() {
        try {
            preSave();
            getService().save(model);
            postSave();
        } catch (Exception ex) {
            addMessage(FacesMessage.SEVERITY_ERROR, getMessageFromI18N("aplicativo.msg.erro.salvar"), ex.getMessage());
            return "";
        }

        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(SUCESSO_SALVAR, true);

        return init();
    }

    public String remover() {
        try {
            getService().remove(model);
        } catch (Exception ex) {
            addMessage(FacesMessage.SEVERITY_ERROR, getMessageFromI18N("aplicativo.msg.erro.remover"), ex.getMessage());
            trataExecaoConstraint(ex);
            return "";
        }

        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(SUCESSO_REMOVER, true);

        return init();
    }

    private void trataExecaoConstraint(Throwable throwable) {
        if (throwable != null) {
            if (throwable instanceof ConstraintViolationException) {
                addMessage(FacesMessage.SEVERITY_ERROR, getMessageFromI18N("aplicativo.msg.erro.remover.registrousado"), null);
            } else {
                trataExecaoConstraint(throwable.getCause());
            }
        }

    }

    public String init() {
        return iniciar(getMenuListar(), getActionListar());
    }

    public T getModel() {
        Object objIdSelecionado = FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("idSelecionado");

        if (objIdSelecionado != null) {
            model = getService().find((Number) objIdSelecionado);
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("idSelecionado", null);
        }

        if (model == null) {
            novo();
        }

        return model;
    }

    public void setModel(T model) {
        this.model = model;
    }

    public List<T> getListaFiltrada() {
        return listaFiltrada;
    }

    public void setListaFiltrada(List<T> listaFiltrada) {
        this.listaFiltrada = listaFiltrada;
    }

}

src/main/webapp/crud/editar.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="/layout/template.xhtml">
	<ui:define name="pageTitle">
		<h:outputText value="#{model.label} - #{msg['aplicativo.label.editar']}" />
	</ui:define>

	<ui:define name="content">
		<ui:include src="/#{bean.diretorio}/form.xhtml">
			<ui:param name="subtitle" value="#{msg['aplicativo.label.editar']}" />
		</ui:include>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/crud/form.xhtml
<ui:fragment xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">

	<h:form prependId="false" styleClass="form-horizontal" acceptcharset="ISO-8859-1">
		<fieldset>
			<legend>
				<h3>
					<h:outputText value="#{bean.label}" />
					<small> <h:outputText value="#{subtitle}" /></small>
				</h3>
			</legend>
			<ui:insert name="formulario"></ui:insert>
		</fieldset>

		<p:spacer />
		<div class="control-group">
			<div class="controls">
				<p:commandButton value="#{msg['aplicativo.button.salvar']}" action="#{bean.salvar}" styleClass="btn btn-success" rendered="#{bean.model != null}" />
				<p:spacer width="5px" />
				<p:commandButton value="#{msg['aplicativo.button.cancelar']}" action="#{bean.init}" styleClass="btn" immediate="true"/>
				<p:spacer width="5px" />
				<p:commandButton value="#{msg['aplicativo.button.excluir']}" onclick="PF('confirmation').show();return false;" rendered="#{bean.model.id != null}" immediate="true" styleClass="btn btn-danger" />
			</div>
		</div>

		<p:confirmDialog id="confirmDialog" message="#{msg['aplicativo.confirmacao.exclusao.registro']}" header="#{msg['aplicativo.confirmacao']}" severity="alert" widgetVar="confirmation">
			<p:commandButton id="aceita" value="#{msg['aplicativo.confirmacao.sim']}" update="messages" oncomplete="PF('confirmation').hide()" action="#{bean.remover}"/>
			<p:commandButton id="declina" value="#{msg['aplicativo.confirmacao.nao']}" onclick="PF('confirmation').hide()" type="button" />
		</p:confirmDialog>
		
	</h:form>
</ui:fragment>

src/main/webapp/crud/incluir.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">

<ui:composition template="/layout/template.xhtml">
	<ui:define name="pageTitle">
		<h:outputText value="#{bean.label} - #{msg['aplicativo.label.incluir']}" />
	</ui:define>

	<ui:define name="content">
		<ui:include src="/#{bean.diretorio}/form.xhtml">
			<ui:param name="subtitle" value="#{msg['aplicativo.label.incluir']}" />
		</ui:include>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/crud/listar.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">

<ui:composition template="/layout/template.xhtml">
	<ui:define name="pageTitle">
		<h:outputText value="#{bean.label} - #{msg['aplicativo.label.listar']}" />
	</ui:define>

	<ui:define name="content">
		<div style="border-bottom: 1px solid #E5E5E5;">
			<h3>
				<h:outputText value="#{bean.label}" />
				<small> <h:outputText value="#{msg['aplicativo.label.listar']}" /></small>
			</h3>
		</div>
		<h:form>
			<div class="control-group">
				<div class="controls">
					<p:commandButton value="#{msg['aplicativo.label.incluir']}" action="#{beanNovo.iniciar()}" styleClass="btn" immediate="true"/>
				</div>
			</div>
			<p:dataTable value="#{bean.listar}" var="model" emptyMessage="Não há registros" widgetVar="dataTable" filteredValue="#{bean.listaFiltrada}">
				<p:column headerText="#" style="width:10%;text-align:center">
					<p:commandLink styleClass="icon-pencil" title="#{msg['aplicativo.label.editar']}" action="#{bean.carregar(model.id)}"/>
				</p:column>
				<ui:insert name="colunas"></ui:insert>
			</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/crud/treetable.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">

<ui:composition template="/layout/template.xhtml">
	<ui:define name="pageTitle">
		<h:outputText value="#{bean.label} - #{msg['aplicativo.label.listar']}" />
	</ui:define>

	<ui:define name="content">
		<div style="border-bottom: 1px solid #E5E5E5;">
			<h3>
				<h:outputText value="#{bean.label}" />
				<small> <h:outputText value="#{msg['aplicativo.label.listar']}" /></small>
			</h3>
		</div>
		<h:form>
			<p:treeTable value="#{bean.root}" var="model" emptyMessage="Não há registros">
				<p:ajax event="expand" listener="#{bean.abreNo}" />
				<p:column headerText="#" style="width:10%;text-align:center">
					<p:commandLink value="#{model.id}" title="#{msg['aplicativo.label.editar']} #{model.id}" action="#{bean.carregar(model.id)}" />
				</p:column>
				<ui:insert name="colunas"></ui:insert>
			</p:treeTable>
		</h:form>
		<h:messages />
	</ui:define>
</ui:composition>
</html>